openshift-helm-charts/development

.github/workflows/build.yml

Adding fix already added to charts repo: https://github.com/openshift-helm-charts/charts/pull/314
Reduce the length of the names used for OCP testing.

reduce length of default string used in createing host name

---

scripts/src/chartprreview/chartprreview.py

Need to skip version check when verifying community charts.

Fixing community path with force-publish label

---

.github/workflows/build.yml
scripts/prepare_pr_comment.py
scripts/src/sanitycheckpr/sanitycheckpr.py

Changing sanity check to add more precise messages around OWNERS file.

Adding better OWNERS related PR messages

---

.github/workflows/schedule.yml

schedule.yml: fix oc version to check server version not client version

---

.github/workflows/schedule.yml

schedule.yml: fix push token to use BOT_TOKEN

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md
release/release_info.json
scripts/setup.cfg
scripts/src/github/gitutils.py
scripts/src/owners/checkuser.py
scripts/src/release/release_info.py
scripts/src/release/releasechecker.py
scripts/src/release/releaser.py
scripts/src/workflowtesting/checkprforci.py

Workflow changes to enable automatic release of workflow changes to the charts repository.
.github/workflows/release.yml is the workflow.
The working is documented in the README.md: https://github.com/mmulholla/development/blob/AutoRelease/README.md

Auto release chart workflows

---

scripts/src/report/report_info.py

Fix problem invoking chart verifier report command fron cert flow

Fix problem with involing report in cert flow

---

.github/workflows/schedule.yml

Made it so the cron job will only run from the openshift-helm-charts/charts repository.
workflow dispatch is not restricted.

prevent cron job running on forks

---

scripts/src/saforcertadmin/cluster_role_binding.yaml
scripts/src/saforcertadmin/create_sa.sh

Tested token produced by this script here: https://github.com/dperaza4dustbit/development/runs/4360138781?check_suite_focus=true
Signed-off-by: David Peraza <dperaza@redhat.com>

Adding script to create admin sa with permanent token duration

---

tests/functional/features/chart_verifier_comes_back_with_failures.feature
tests/functional/step_defs/test_chart_verifier_comes_back_with_failures.py
tests/functional/utils/chart_certification.py

This PR will cover story : https://issues.redhat.com/browse/HELM-243

Added chart-verifier comes back with failure scenario

---

tests/functional/features/invalid_url_in_the_report.feature
tests/functional/features/sha_value_does_not_match.feature
tests/functional/step_defs/test_invalid_url_in_the_report.py
tests/functional/step_defs/test_sha_value_does_not_match.py
tests/functional/utils/chart_certification.py

This PR will cover below stories: 
https://issues.redhat.com/browse/HELM-265
https://issues.redhat.com/browse/HELM-280

Added sha value mismatch and invalid url test scenarios

---

tests/functional/features/pr_includes_a_file_which_is_not_chart_related.feature
tests/functional/step_defs/test_pr_includes_a_file_which_is_not_related.py
tests/functional/utils/chart_certification.py

This PR will cover story: https://issues.redhat.com/browse/HELM-266

Added test scenario: PR includes a non chart related file

---

tests/functional/features/user_submits_chart_with_errors.feature
tests/functional/step_defs/conftest.py

It will resolve the test run failures when running in fork with different BOT_NAME as observed in below run.
https://github.com/mmulholla/development/runs/4472014139?check_suite_focus=true#step:7:132

Fix the test failures when running in fork

---

.github/workflows/build.yml

Update workflow to use the downloaded chart releaser in https://github.com/openshift-helm-charts/development/pull/85

add use of downloaded helm chart releaser in the workflow

---

tests/functional/features/chart_verifier_comes_back_with_failures.feature
tests/functional/features/pr_includes_a_file_which_is_not_chart_related.feature
tests/functional/features/sha_value_does_not_match.feature
tests/functional/step_defs/conftest.py
tests/functional/step_defs/test_chart_verifier_comes_back_with_failures.py
tests/functional/step_defs/test_invalid_url_in_the_report.py
tests/functional/step_defs/test_pr_includes_a_file_which_is_not_related.py
tests/functional/step_defs/test_sha_value_does_not_match.py

This PR completes the work done in  PR https://github.com/openshift-helm-charts/development/pull/83

Refactored the latest scripts using conftest.py

---

scripts/src/chartprreview/chartprreview.py
scripts/src/report/report_info.py

Modify flows to expect chart verifier report to be output to stdout.

Update for chart-verifier report to stdout

---

.github/workflows/build.yml
.github/workflows/release.yml
scripts/src/release/releaser.py
tests/functional/utils/chart_certification.py

Various fixes for the release process to start working again. Mostly reverting (#73)

fixes for release processing

---

release/release_info.json

Release 1.2.0

---

.github/workflows/nightly_test.yml

This PR will fix the nightly scheduled workflow failure : https://github.com/openshift-helm-charts/development/actions/runs/1827465328

Fixes the nightly workflow failure

---

.github/workflows/nightly_test.yml

This PR will fix the nightly test workflow failure: https://github.com/openshift-helm-charts/development/actions/runs/1832644315

Fixed the nightly workflow failure

---

.github/workflows/build.yml
scripts/src/chartprreview/chartprreview.py

chartprreview.py:
- Now that the verifier outputs errors to stderr - I added code to check for stderr and output the content.
- Removed one print out of the report as it will be printed later.
build.yml:
Delete Namespace was not being called as it was checking for a non existent output. Fixed it.

print errors from verifier and ensure delete namespace is called

---

.github/workflows/metrics.yml
scripts/setup.cfg

Update flow to fully initialize python as per our other flow.
Also added workflow dis[patch so we can run (and test) on demand.

initialise python in metrics flow

---

.github/workflows/schedule.yml

chart verifier run never runs because output step check is incorrect.

Fix typo in chartverifier job

---

release/release_info.json

Release includes:
- Add support for provider delivery control (#110).
- Ensure delete namespace is called (#113).
- Test and workflow improvements.

Release 1.3.0

---

.github/workflows/metrics.yml
scripts/requirements.txt
scripts/src/indexfile/index.py
scripts/src/metrics/metrics.py

Now using python analytics library i stead using HTTP requests - make the code a lot simpler and fixes problem where HTTP code was not uploading.
metrics scripts also includes code ready for pull request metrics.
also added code so that data uploaded now looks like this: 
analytics.track('HashiCorp', 'vault downloads', {
'hashicorp-vault-0.14.0.tgz': 78
})
this makes the data more granular
This adds a new file index.py most of which was taken from @dperaza4dustbit python script which reads the index file.

Use python library for analytics

---

scripts/requirements.txt
scripts/src/saforcertadmin/push_secrets.py

This PR is an part of the work required for story https://issues.redhat.com/browse/HELM-325
Running the script with appropriate authorization will update the secrets in a github repository.
Signed-off-by: Sushanta Das <sushanta.das.ju@gmail.com>

Script to push github secrets

---

.github/workflows/build.yml
scripts/setup.cfg
scripts/src/chartprreview/chartprreview.py
scripts/src/release/releaser.py
scripts/src/report/get_verify_params.py
scripts/src/report/report_info.py
scripts/src/saforcharttesting/saforcharttesting.py
tests/functional/utils/chart_certification.py

Have updated the flow to use the chart verifier action to create the report and the report summary and as a result the code required to generate those is no longer needed.
Also updated the flow to use existing actions to perform oc install and oc login helping to simplify the workflow.
There were knock on affects in may parts of the scripts which support the flow.

Use chart verifier and oc actions

---

.github/workflows/metrics.yml
scripts/src/metrics/metrics.py

passed the github token to the metrics code to hopefully get a larger rate limit. Also added output of rate limit for information (note: rate limit checks do not count towards the rate limit)

Increase rate limit using github token

---

charts/partners/Mavenir/testchart1/OWNERS

Same change as went into the main repo: https://github.com/openshift-helm-charts/charts/pull/497

remove erroneous mavenir OWNER file

---

scripts/requirements.txt
tests/functional/behave_features/HC-01_chart_src_without_report.feature
tests/functional/behave_features/HC-02_chart_tar_without_report.feature
tests/functional/behave_features/common/utils/chart.py
tests/functional/behave_features/common/utils/chart_certification.py
tests/functional/behave_features/common/utils/github.py
tests/functional/behave_features/common/utils/notifier.py
tests/functional/behave_features/common/utils/secret.py
tests/functional/behave_features/common/utils/set_directory.py
tests/functional/behave_features/common/utils/setttings.py
tests/functional/behave_features/environment.py
tests/functional/behave_features/steps/implementation.py

This PR addressed story: https://issues.redhat.com/browse/HELM-375
Migrated two basic scenarios from the certification flow tests. No changes has been done in the test or release workflows.
To run all scenarios use below command:
`ve1/bin/behave tests/functional/behave_features/`
To run only the smoke scenarios use below command:
`ve1/bin/behave tests/functional/behave_features/ --tags=smoke`

changes related to framework migration to behave

---

.github/workflows/build.yml
scripts/src/saforcharttesting/saforcharttesting.py

certification flow was failing while creating sa token for chart testing in 4.11 here https://github.com/openshift-helm-charts/sandbox/runs/7899234015?check_suite_focus=true#step:20:21
It fixes the issue.

Fixes the sa token creation failure in 4.11

---

release/release_info.json

release PR with the fix of sa token creation

New release 1.4.2

---

tests/functional/behave_features/HC-14_user_submits_chart_with_errors.feature
tests/functional/behave_features/common/utils/chart_certification.py
tests/functional/behave_features/steps/implementation.py

It will address story: https://issues.redhat.com/browse/HELM-409

Added test for bad semantic version

---

scripts/requirements.txt

This PR is to address the dependabot alert here https://github.com/openshift-helm-charts/charts/security/dependabot/1

Bump Mako==1.2.3: dependabot alert

---

scripts/src/metrics/metrics.py

This PR makes changes to Chart downloads metrics made on the segment, so as to write data for top 5 charts and rank the charts with respect to number of downloads.
https://issues.redhat.com/browse/HELM-376 
Signed-off-by: Kartikey Mamgain [mamgainkartikey@gmail.com](mailto:mamgainkartikey@gmail.com)

Chart Downloads v1.0 

---

.github/workflows/build.yml
scripts/src/metrics/metrics.py

This PR makes changes to PR submission, merge and outocome made on the segment.
Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>

Changes Made for PR submission, Merge and Outcome Segment Data

---

.github/workflows/owners.yml
scripts/setup.cfg
scripts/src/metrics/pushowners.py
scripts/src/owners/owners_file.py

This PR aims at creating a new workflow to be triggered on a push request. If the request is from the redhat-mercury-bot for an OWNERS file create or update a new stat should be listed in the segment.
Please refer to story https://issues.redhat.com/browse/HELM-417 for more details.

Owner Metrics

---

.github/workflows/metrics.yml
scripts/src/metrics/metrics.py

This PR aims at adding prefix as param to downloads metrics.
Signed-off-by: Kartikey_star <41898282+github-actions[bot]@users.noreply.github.com>

add prefix to downloads

---

.github/workflows/release.yml
README.md
release/release_info.json
scripts/src/release/release_info.py
scripts/src/release/releaser.py
scripts/src/tools/gitutils.py

This PR is part of the work for story: https://issues.redhat.com/browse/HELM-395

Release changes for stage repo

---

release/release_info.json

New Certification flow Release 1.5.0

Release 1.5.0

---

.github/workflows/codeql.yml
release/release_info.json

This PR is aimed at adding codeQL workflow for static code analysis .
Signed-off-by: Kartikey Mamgain [mamgainkartikey@gmail.com](mailto:mamgainkartikey@gmail.com)

Static code analysis workflow

---

.github/workflows/build.yml
scripts/src/metrics/metrics.py

This PR updates the getChartUpdate to search for partners if provider type used in segment is partner , so as to match our directory structure.
Signed-off-by: Kartikey-star <41898282+github-actions[bot]@users.noreply.github.com>

search for partners in directory if provider type is partner

---

.github/workflows/test.yml

Need for upcoming changes to tests

add bot token for check_request step

---

.github/workflows/release.yml

Need for upcoming changes to tests

Set bot token for python scripts

---

.github/workflows/build.yml
.github/workflows/metrics.yml
scripts/src/chartprreview/chartprreview.py
scripts/src/chartrepomanager/chartrepomanager.py
scripts/src/chartrepomanager/indexannotations.py
scripts/src/checkautomerge/checkautomerge.py
scripts/src/checkprcontent/checkpr.py
scripts/src/metrics/metrics.py
scripts/src/metrics/pushowners.py
scripts/src/owners/checkuser.py
scripts/src/owners/owners_file.py
scripts/src/pullrequest/prartifact.py
scripts/src/release/releasechecker.py
scripts/src/report/verifier_report.py
scripts/src/saforcertadmin/push_secrets.py
scripts/src/signedchart/signedchart.py
scripts/src/tools/gitutils.py
scripts/src/workflowtesting/checkprforci.py

add code so that provider delivery and web catalog only are treated as he same thing.  
also fix failing builds:
add authorization token to header for github api requests
correctly process response when request return a failure message.
Moved code o get files and label to a common function which caches results.
output api rate limit data after api calls.

Web catalog only

---

scripts/src/metrics/metrics.py

This PR will fix the nightly metrics workflow run failure here https://github.com/openshift-helm-charts/development/actions/runs/3888745805/jobs/6636375690

Fixed the metrics workflow failure

---

.github/workflows/codeql.yml
.github/workflows/metrics.yml
.github/workflows/nightly_test.yml
.github/workflows/version_check.yml

This PR will address story https://issues.redhat.com/browse/HELM-444 
Also added change to stop CodeQL analysis job to run on forked repos.

Added change to send notification based on job status

---

.github/workflows/metrics.yml
.github/workflows/nightly_test.yml
.github/workflows/version_check.yml

This will fix the notification not being sent when the previous step fails.

Fix: Always send the notification evenif the previous step fails

---

.github/workflows/release.yml
scripts/src/release/releasechecker.py
scripts/src/tools/gitutils.py

Various fixes to get the release working.

fixes for release workflow

---

release/release_info.json

This release includes @itroyano's contribution, fixing an issue where the Bot automation would post a success comment in cases where certain tasks did not actually succeed (E.g. cluster login). Now you require explicit success, and we fail back to failure.

Release 1.5.3

---

release/release_info.json

Contains bugfix for handling annotations on community submissions.

Release 1.5.6

---

OWNERS

@mgoerens is cleaning up workflow related things. Add them as an approver so that certain tests can work as expected.

Add mgoerens as approver

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/mercury_bot.yml
.github/workflows/metrics.yml
.github/workflows/nightly_test.yml
.github/workflows/owners.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/token.yml
.github/workflows/version_check.yml

Let me know if I should create an GitHub issue first and where (in /charts vs this repo ?)

Update Github actions that use deprecated Node12

---

OWNERS

Unblocked @OchiengEd from being able to update workflows in PR https://github.com/openshift-helm-charts/development/pull/250

Add OchiengEd as approver/reviewer to update workflows

---

release/release_info.json

* Add mgoerens as approver by @komish in https://github.com/openshift-helm-charts/development/pull/248
* Apply black and fix some PEP8 violations by @mgoerens in https://github.com/openshift-helm-charts/development/pull/247
* Update Github actions that use deprecated Node12 by @mgoerens in https://github.com/openshift-helm-charts/development/pull/246
* Create action to disable specific workflows based on repo config by @komish in https://github.com/openshift-helm-charts/development/pull/249
* Add OchiengEd as approver/reviewer to update workflows by @komish in https://github.com/openshift-helm-charts/development/pull/251
* Update vault chart fixtures for chart testing fix by @jsm84 in https://github.com/openshift-helm-charts/development/pull/252
* Updated reports for vault chart fixtures …

Release 1.5.8

---

.github/workflows/build.yml

Update actions/github-script package to v6 to migrate from `node12` to `node16`

Update actions/github-script version

---

scripts/src/workflowtesting/checkprforci.py

This PR just fixes a formatting error caught by Black for a script that may have been missing at the time Black was introduced into our CI.

Apply Black formatter

---

release/release_info.json

Quite a few changes landing here, including workflows, scripts, etc. Bumping the Y-stream number for these reasons.

Release 1.6.0

---

docs/README.md
docs/pull-request.md

This PR adds documentation outlining the basics of testing workflow changes in a PR so that developers need not rely on PRs to confirm everything is healthy.
This doc specifically covers testing of workflow changes. It does not cover running Behave testing (e.g. smoke, e2e, etc). This will be added in the future as this requires a bit more plumbing.

Expand docs covering how to test workflow and script changes in a fork

---

tests/functional/behave_features/common/utils/chart_certification.py

Don't try to delete a release that is not found

---

.github/actions/get-ocp-range/action.yaml
.github/workflows/build.yml
.github/workflows/check-contributor.yml
.github/workflows/codeql.yml
.github/workflows/mercury_bot.yml
.github/workflows/metrics.yml
.github/workflows/nightly_test.yml
.github/workflows/owners.yml
.github/workflows/python-style.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/version_check.yml

Several actions now use Node20 instead of Node16.

Update github actions to latest versions

---

.github/actions/generate-chart-locks/action.yaml
.github/workflows/build.yml
.github/workflows/check-locks-on-owners-submission.yml
.github/workflows/lock-sanity-check.yml
.github/workflows/mercury_bot.yml
.github/workflows/owners-redhat.yml
.github/workflows/owners.yml

Fixes #333 
This PR looks at our currently used runners, and collapses like runner versions to be the latest version present in our workflows.

Standardize action runner versions across workflows

---

scripts/src/metrics/pushowners.py
scripts/src/owners/owners_file.py
scripts/src/signedchart/signedchart.py

Rework owners_file.py and add custom exception

---

tests/functional/behave_features/common/utils/chart_certification.py
tests/functional/behave_features/common/utils/github.py

Fix empty PR number in tests logs

---

scripts/src/precheck/serializer_test.py
scripts/src/precheck/submission.py
scripts/src/precheck/submission_test.py

This commits ports the "check_web_catalog_only" from the checkpr package over to the Submission data structure.

Add check for web_catalog_only to Submission

---

.github/workflows/build.yml

We don't want to be pinged from sandbox (see this PR for instance https://github.com/openshift-helm-charts/sandbox/pull/92390). Hence fixing broken conditioning

Use Github context in tasks conditions

---

scripts/src/precheck/submission.py
scripts/src/precheck/submission_test.py

Ported from:
https://github.com/openshift-helm-charts/development/blob/919146bc199e6366c40cf10d533d4669bd3def70/scripts/src/checkprcontent/checkpr.py#L211-L222

Add redhat prefix check

---

scripts/src/submission/submission.py

In the case where the submission only contains an OWNERS file, it does not relate to a specific chart's version. In particular, there is no version that can be inferred from the directory structure. Hence this should be an optional parameter when registering chart's information.

Set version as optional when for Charts

---

.github/workflows/build.yml

Following up on the #409, applying #405 changes.

Finish consolidating the python setup steps

---

.github/workflows/build.yml

Debug to better understand #432

Add debug for tracking GITHUB_REF value
