openshift-helm-charts/development

docs/README.md
There has been a lot of confusion from multiple partners thinking they have
to send the OWNERs file in a PR. Clarifying the wording here around the difference
between partners, redhat and community when it comes to OWNERs file genesis.
=> Update the documentation to clarify OWNERs file submission for partners.

.github/workflows/schedule.yml, .github/workflows/test.yml
Setting the traceback flag to false to avoid traceback printing
partial github token characters. We will need to rotate all our
github tokens after this PR merges.
=> Fixing a security issue when running pytest

scripts/src/chartrepomanager/chartrepomanager.py
We found a bug on our regular expression no covering a version format we should support.
=> Fixing semver regular expression

tests/functional/test_submitted_charts.py
This avoids collision between test runs of oc change and chart-verifier
change.
=> test_submitted_charts: add software name to branch names

scripts/src/saforcharttesting/saforcharttesting.py
Helm uninstall was failing in workflow, 
[ERROR} Error from helm uninstall : Error running process: executing helm with args "uninstall vault-ia25nn4fek --namespace charts-157 []": exit status 1
---
Error: uninstallation completed with 4 error(s): clusterrolebindings.rbac.authorization.k8s.io "vault-ia25nn4fek-server-binding" is forbidden: User "system:serviceaccount:charts-157:charts-157" cannot delete resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope; clusterrolebindings.rbac.authorization.k8s.io "vault-ia25nn4fek-agent-injector-binding" is forbidden: User "system:serviceaccount:charts-157:charts-157" cannot delete resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope; …
=> Enable cluster role deletes in helm uninstall

.github/workflows/test.yml, tests/functional/test_chart_src_with_report.py, tests/functional/test_chart_src_without_report.py, tests/functional/test_chart_tar_with_report.py, tests/functional/test_chart_tar_without_report.py, tests/functional/test_report_only_no_errors.py, tests/functional/utils.py
In order to avoid release name to collide when two PRs are send
for testing at the same time. Vendor it is used as organization
in the release name template.
=> Add unique vendor name to each test case

.github/workflows/build.yml, scripts/src/chartrepomanager/chartrepomanager.py, scripts/src/sanitycheckpr/sanitycheckpr.py, tests/functional/test_chart_src_with_report.py, tests/functional/test_chart_src_without_report.py, tests/functional/test_chart_tar_with_report.py, tests/functional/test_chart_tar_without_report.py, tests/functional/test_submitted_charts.py
This commit reverts changes introduced in
https://github.com/openshift-helm-charts/charts/pull/294 because we
don't want to add test logic to `scripts/` and a more test specific fix
was implemented: https://github.com/openshift-helm-charts/development/commit/54ba09ae7b8fc4d032e582990e9e9bcf15a03b56
Closes: https://issues.redhat.com/browse/HELM-233
=> revert: charts/pull/294

.github/workflows/build.yml, .github/workflows/release.yml, README.md, scripts/src/github/gitutils.py, scripts/src/owners/checkuser.py, scripts/src/release/releasechecker.py, scripts/src/release/releaser.py
Updated auto-release to create a PR for the chart updates to the development repository. 
This PR will  then be detected and auto-merged. After auto-merge the release is created.
.github/workflows/release.yml contains a lot of changes as it is now dual purpose:
1. Create the PR's 
2. detect the development PR and auto-merge it.  
.github/workflows/build.yml was also updated to ignore the development PR.
I also improved the code to make it better at handling errors form github and to cater for corner cases such as the dev pr being not needed , in which case the release is created as part of release/release.info processing step.
Have fully tested and comfortable it works.
=> Dev pr for auto release

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml, scripts/src/github/gitutils.py, scripts/src/release/releasechecker.py, scripts/src/release/releaser.py
Updated the test workflow to look if the PR is a charts release PR and if it is, the PR is auto-merged.
Also made changes to remove the need to modify some files when testing. This is new behavior
The PR with a ```release-info.json``` file is targetted at a repository and a branch. 
1. The repository has to end with ```/development```  so, for example  ```mmulholla/development```  is good. The ```mmulholla``` part is the organization.  
2. The charts PR will be sent to the same organization and same branch but to "/charts"
3. The dev PR will be sent to the same repository and branch as the original PR was sent to.
Example: 
- I create a branch containing only the  ```release-info.json``` and create a PR to merge into branch ```test-branch``` on my fork ```mmulholla/development```.
- The …
=> Enable auto merge of charts pr as part of release processing

scripts/src/chartprreview/chartprreview.py
DO NOT MERGE because it needs to be merged shortly after: https://github.com/redhat-certification/chart-verifier/pull/213
Add logic to recognize the new annotations added:
- charts.openshift.io/testedOpenShiftVersion
- renamed from charts.openshift.io/certifiedOpenShiftVersions
- charts.openshift.io/supportedOpenShiftVersions
-  new, based on content of kubeVersion in chart.yaml.
=> Ensure worklfow works with new annotations

.github/workflows/build.yml
specify --insecure-skip-tls-verify  on oc login if not main repo.
This should help us testing on fork, let me know if you think it should be more restrictive.
=> Diff oc login if not main repo

tests/functional/utils/chart_certification.py
Changing the unique vendor logic to include a timestamp no matter
what.
Signed-off-by: David Peraza <dperaza@redhat.com>
=> Making test releases being unique

scripts/requirements.txt, scripts/src/chartprreview/chartprreview.py, scripts/src/chartrepomanager/chartrepomanager.py, scripts/src/chartrepomanager/indexannotations.py
If chart submission is a 1.0 report:
1. rename certifiedOpenShiftVersions annotation to testedOpenShiftVersion
2. Add a supportedOpenShiftVersions based on the kubeVersion in the chart. If kubeVersion is not recognizable as a version set this to N/A,
Tested with a new and old report (report only submissions:
new report: https://github.com/mmulholla/development/pull/174
old report: https://github.com/mmulholla/development/pull/175
resulting Index:
https://github.com/mmulholla/development/blob/gh-pages/index.yaml
=> modify annotations for 1.0 report in index.yaml

scripts/src/chartrepomanager/indexannotations.py
We are not checking if kubeVersion is in chart before trying to get the value. This is causing redhat and comunity charts that dont have kubeVersion set to fail on release step.
=> Fix community and redhat path when kubeVersion not set in chart

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml
Caused by unpredicted single(')/double(") quotes in PR body, shell strings in
workflow produce unmatched quotes error. This change ensures we parse
the string correctly before passing as arguments.
Refer: https://github.com/openshift-helm-charts/development/runs/4266289403?check_suite_focus=true#step:7:14
=> .github: fix unmatched quotes in workflows

scripts/src/chartprreview/chartprreview.py, scripts/src/report/verifier_report.py
Included as a comment in the python script:
```
Used by github actions,specifically as part of the charts auto release process defined in
.github/workflow/release.yml.
Used to loosely determine if a submitted report is valid and has not been tampered with.
An invalid valid report:
- does not load as a yaml file.
- does not include  a "kind" attribute set the "verify-report" .
- does not include sections: "tool.metadata", "tool.chart", "results".
A tampered report is only determined if the chart-testing check has passed:
- certifiedOpenShiftVersions or testOpenShiftVersion contain valid semantic versions.
- certifiedOpenShiftVersions or testOpenShiftVersion specify an OCP version with helm support  (>=4.1.0)
- if the has-kubeversion check has also passed
- v1.0 profile:
- if a valid …
```
=> Add validation of a report in pr review

.github/workflows/build.yml, scripts/prepare_pr_comment.py, scripts/src/chartprreview/chartprreview.py, tests/functional/features/chart_src_without_report.feature, tests/functional/features/chart_tar_without_report.feature, tests/functional/features/chart_verifier_comes_back_with_failures.feature, tests/functional/features/report_and_chart_src.feature, tests/functional/features/report_and_chart_tar.feature, tests/functional/features/report_without_chart.feature
PR messages have been updated:
A new footer was added for all messages (e.g.: https://github.com/openshift-helm-charts/sandbox/pull/8335) to address:
https://issues.redhat.com/browse/HELM-239
---
```
For information on the certification process see:
- [Red Hat certification requirements and process for Kubernetes applications that are deployed using Helm charts.](https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/helm-chart-certification/overview).
For support, connect with our [Technology Partner Success Desk](https://redhat-connect.gitbook.io/red-hat-partner-connect-general-guide/managing-your-account/getting-help/technology-partner-success-desk).
/metadata {"vendor_label": "hashicorp-2d80e8b8b4ca4474993740175807f747-93", "chart_name": "vault"}
``` …
=> Improve messages in error situations

.github/workflows/nightly_test.yml
This PR will disable the workflow run the forks, since the nightly test is only intended for 'openshift-helm-charts/development' repo.
=> disable the nightly workflow in forks

scripts/src/chartrepomanager/chartrepomanager.py, tests/functional/step_defs/test_provider_delivery_control.py
Two issues.
1. When deciding which index file to use the test checked for ```os.environ["PROVIDER_DELIVERY"]``` as a binary, but it is a string. As a result everything went to Index.yaml.
2. The test case missed out the call to check the content of the new index file.
=> fix bug in ProviderDelivery

.github/workflows/metrics.yaml, .github/workflows/metrics.yml, release/release_info.json, scripts/src/metrics/metrics.py
Adds a github cron job that runs a python script that will collect the
accumulated download count from release artifacts and send over to
Segment. Eventually the metrics will land in Woopra for analytics.
Closes: https://issues.redhat.com/browse/HELM-193
Signed-off-by: Allen Bai <carpe.diem.allen@gmail.com>
@mmulholla added changes:
- only run cron job on development branch
- do not copy metrics.yml to charts repository as part of a release
- accept any 2xx return code from request for release info or posting info to segment 
- added slack channel message with outcome.
=> metrics: add job to collect and send metrics

.github/workflows/schedule.yml
Add slack notification if a test is run either due to a OCP version update or chart verifier version update.
=> Add slack notification if tests are run

.github/workflows/build.yml, .github/workflows/metrics.yml, scripts/prepare_pr_comment.py, scripts/src/checkprcontent/checkpr.py, scripts/src/metrics/metrics.py
- Added metrics each time a chart PR runs. Added at then end of the workflow so does not affect merge if it fails for any reason.
- Modified release metrics to log a single metric for all versions of the same chart. This should prevent woopra showing lots of zeros.
- Added the concept of a test segment write key and  production write key read from secrets
- SEGMENT_WRITE_KEY - production key
- SEGMENT_TEST_WRITE_KEY - test key
- Added a workflow-dispatch for the metrics workflow, takes a single boolean input to se which segment write key to use.
- dispatch workflow can be run form forks.
This PR was created for: https://issues.redhat.com/browse/HELM-302
=> add PR metrics and update release metrics

.github/workflows/metrics.yml
Fixed the workflow bash to prevent error in schedule metrics.
=> Fix bash error in metrics workflow

tests/functional/features/HC-06_provider_delivery_control.feature
Since the earlier step definition is also processing report, it resulted in one test failure in nightly run. Used the step definition where we are not processing the report from conftest.py
=> changed to correct step definition

.github/workflows/version_check.yml, tests/functional/utils/chart_certification.py, tests/functional/utils/github.py, tests/functional/utils/notifier.py
Fixes:
- https://issues.redhat.com/browse/HELM-337
- https://issues.redhat.com/browse/HELM-338
Made quite a few changes:
- Fixed the flows so they actually work.
- Issues are only opened if a chart has a failure.
- In the issues dperaza and mmulholla are tagged not the chart owners.
- The issue should then be reviewed to ensure it is correct before tagging the owners.
- Updated the content of any issues opened.
- Issues are also opened for a dry run but in openshift-helm-charts/sandbox, the issue titles start ```Dry Run:```
- Dry run will run the checks whether or not version changes are detected.
- Dry run will work from a fork.
- Added a bunch of logging for easier diagnosis of failures.
- Testing hit some issues with the secondary api rate limit from github which happens when a …
=> Update version checking workflow

.github/workflows/version_check.yml, scripts/src/release/releaser.py, tests/functional/step_defs/test_smoke_scenarios.py
The release build failed because the script was expecting to update file schedule.yml which is now renamed to version_check.yml. Further even with the correct name it would have failed because the cron job invocation was incorrectly in the development version of version_check.yml so it is now removed. '
Also added a quick fix for the smoke tests to fix the provider delivery control failure (test problem)
=> version_check changes needed for release

scripts/src/checkprcontent/checkpr.py
Improved error message and added an exit after detecting multiple charts in a PR.
Test framework does not support adding a multi-chart PR see: https://issues.redhat.com/browse/HELM-368
Manual test was performed see: https://github.com/mmulholla/development/pull/286
This PR addresses bug: https://issues.redhat.com/browse/HELM-365
=> Exit early if more that one chart in a PR

.github/workflows/version_check.yml
https://issues.redhat.com/browse/HELM-383
Fixed formatting error in the bash script part of a step. 
The problem happened because some of the workflow only ran in the schedule job. As a result I also updated the flow to:
1. enable the entire workflow to be tested by adding a new update-version file attribute to the  manual run.
2. Enable the flow to modify a local copy of the software-version file for a manual workflow run not in the charts repo.  
Finally I update the two jobs to run synchronously to prevent a conflict when updating the software version file.
As a result the workflow has been fully tested.
=> Fix bash error and update workflow to enable better testing

tests/functional/behave_features/common/utils/chart_certification.py
Fixes the current smoke test run failure on PR.
https://github.com/openshift-helm-charts/development/runs/7631696491?check_suite_focus=true
It was failing due to we were trying to get the branch name from a detached HEAD state. This part of the code helps us to move back to the current branch when running locally. We now need to set LOCAL_RUN environment, if we are running test locally.
Tested the change on my fork here https://github.com/tisutisu/development/runs/7646415155?check_suite_focus=true
=> Smoke fail fix

.github/workflows/build.yml, scripts/src/chartrepomanager/indexannotations.py, scripts/src/indexfile/index.py, tests/functional/utils/chart_certification.py, tests/functional/utils/github.py, tests/functional/utils/index.py, tests/functional/utils/notifier.py
https://issues.redhat.com/browse/HELM-358
Updated version check workflow to check that the OCP Versions or kubeVersion of all charts  (latest version only) in index.yaml include the OCP version which caused the workflow to run.  
For this needed a mew message when opening a PR, for example:
```
FYI @mmulholla, we checked the OCP versions supported by ibm ibm-oms-ent-prod 6.0.2 because the workflow now supports OpenShift version 4.10.25. We have found that chart ibm-oms-ent-prod 6.0.2 kubeVersion 1.16.0-0 (OCP: 4.3) does not include latest OCP version 4.10.25. Chart owners are: ['ntinvo']
``` 
also improved other messages. 
Also a fix to read the OCP version to kubeVersion map from a chart verifier file so we have a single source.
=> check OCP version support in index.yaml

.github/workflows/build.yml, scripts/src/checkprcontent/checkpr.py, scripts/src/pullrequest/prepare_pr_comment.py, scripts/src/report/verifier_report.py, tests/functional/behave_features/HC-14_user_submits_chart_with_errors.feature
Added an early check for the version based on the directory structure to be valid semantic version and error if it is not. Current test suite does not support creating a chart in a directory with an invalid semantic version so have opened a jira story to add this: https://issues.redhat.com/browse/HELM-409
A manual test can be seen here: https://github.com/mmulholla/development/pull/309
Also added code to handle the chart verifier step ending in an error and not producing a report. This could happen, for example, if the directory structure uses a valid chart version but the chart itself includes a version which is not a valid semantic version. Added a  test for this as it was a simple addition. Note: without this fix, certification would fail but the message added to the PR said the chart …
=> Check chart version is a valid semantic version

tests/functional/behave_features/HC-19_report_sha.feature
Problem was cause by a change to the chart verifier where a message was changed from:
- Digest in report did not match report content 
to:
- digest in report did not match report content
so Digest -> digest
Unfortunately this broke the test,
=> Fix tests - report sha message case

scripts/src/chartprreview/chartprreview.py, scripts/src/owners/owners_file.py, scripts/src/report/get_verify_params.py, scripts/src/report/verifier_report.py, scripts/src/signedchart/signedchart.py
This code correctly process signed charts and pgp key IN OWNERS for certification purposes but has not changed release processing asper the scope of the helm story: https://issues.redhat.com/browse/HELM-411.
I did a lot of manual testing to conform function. Automated test are also a different story.
Manual tests as follows:
- Pass as expected (PR merged):
- No key in OWNERS, signed chart, no report
- No Key in OWNERS, signed chart,  report not for signed chart
- Key in OWNERS, signed chart, no report
- Key in OWNERS, signed chart, report for signed chart
- Key in OWNERS, no chart, report for signed chart
- Key in OWNERS, not signed chart, signed chart in report
- Key in OWNERS, no chart, report for a non signed chart
- Key in OWNERS, non signed  chart, no report
- Failed as expected:
- …
=> add support for signed charts

docs/README.md, scripts/src/checkprcontent/checkpr.py, tests/functional/behave_features/HC-06_provider_delivery_control.feature
Jira: https://issues.redhat.com/browse/HELM-462
Updates the error messages whenever there is an issue with provider delivery to now display web catalog only. 
The mention of provider controlled delivery in the error messages can lead to some confusions with users. This is due to the fact that the [Creating a Helm Chart Certification Project](https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/helm-chart-certification/creating-a-helm-chart-certification-project) article does not have any mentions of a provider delivery distribution method. In our case provider delivery is the same as the web catalog only distribution method.
=> Update provider delivery message to web catalog only

scripts/src/chartrepomanager/chartrepomanager.py
when providerDelivery flag was set to true, in the commit history log will print the exact file it changed.
Observed wrong commit messge issue here https://github.com/openshift-helm-charts/stage/pull/16
=> Updates git commit log with indexfile name

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/token.yml, .github/workflows/version_check.yml, scripts/src/chartprreview/chartprreview.py, scripts/src/chartrepomanager/chartrepomanager.py, scripts/src/checkprcontent/checkpr.py, scripts/src/pullrequest/prartifact.py, scripts/src/pullrequest/prepare_pr_comment.py, scripts/src/release/releasechecker.py, scripts/src/release/releaser.py, scripts/src/report/get_verify_params.py, scripts/src/tools/gitutils.py, scripts/src/workflowtesting/checkprforci.py
Jira: https://issues.redhat.com/browse/HELM-437
Removes the deprecated set-output in favore for GITHUB_OUTPUT
The workflows and associated scripts make extensive use of set-output, but it is now being deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This PR removes set-output and replaces it with GITHUB_OUTPUT within the workflow. It also introduces an addition function within the tools module that will handle adding the output to GITHUB_OUTPUT for the python scripts.
=> Deprecation of set-output

scripts/src/checkprcontent/checkpr.py, scripts/src/pullrequest/prartifact.py
Added some code to error if the tarbal name is bad. 
See: https://issues.redhat.com/browse/HELM-382
Confirmed it worked manualy, this ii the PR:
```
Thank you for submitting PR #391 for Helm Chart Certification!
One or more errors were found with the pull request: 
[ERROR] the tgz file is named incorrectly. Expected: psql-service-0.1.12.tgz
```
=> Create error if tarball name not as expected

tests/data/HC-10/signed_chart/report/partner/report.yaml, tests/data/HC-10/signed_chart/report/redhat/report.yaml, tests/functional/behave_features/HC-10_signed_chart.feature
Commented one scenario, while testing signed chart with wrong key in OWNERS file for vendorProfile: redhat, PR got successfully merged here https://github.com/openshift-helm-charts/sandbox/pull/44260
Expecting it to fail with error: Signature verification failed.
=> Adding feature file for signed chart tests

.github/workflows/build.yml
Hopefully a fix for issue when force-publish is added the a PR the merge fails due to lack of permissions.
=> use bot token for merge

OWNERS
Updates the top-level owners file for this repository to match the charts repo.
=> Add OpDev maintainers as owners

.github/workflows/build.yml
The cluster currently used for testing utilizes a self-signed cert local to the cluster. The charts repo enforced strict tls verification for oc login while other repos did not.
This resolves the issue temporarily until either (a) the cluster LB endpoint uses valid certificates, or (b) the signing key is pulled and added to oc login.
=> allow insecure-skip-tls-verify for charts repo

release/release_info.json
Puts in some fixes that are blocking the production charts/ repo with the new 4.12 cluster.
=> Release 1.5.2

scripts/src/pullrequest/prepare_pr_comment.py
The generic failure did not initialize the `msg` variable, so writing the PR content would fail.
=> Fix variable reference before assignment in generic fail comment

tests/functional/behave_features/HC-16_chart_test_takes_more_than_30mins.feature
Chart Verifier recently ran style tooling which enforced that error messages should not start with capital letters, or end with punctuation. As a result, this feature contains a message string that directly corresponded to a capital letter that was previously used. This PR replaces that with a lower case letter to align the two.
=> adjust case of an error prefix produced by chart-verifier

.github/workflows/mercury_bot.yml
HELM-487 - The Mercury Bot PR-based workflow that's being tested in stage would fail to pull the changes in the invoking PR because the BOT_TOKEN secret was not being passed into the workflow.
This PR adds that context to the specific task.
=> Add missing BOT_TOKEN environment variable in Mercury Bot workflow

scripts/src/chartrepomanager/chartrepomanager.py
Fixes: https://github.com/openshift-helm-charts/charts/issues/894
When chart-only PRs are submitted, our automation extracts annotations that would otherwise have been submitted in a report from the report generated on the partner's behalf. These annotations were then replacing the existing annotations in a given chart instead of merging with them.
This PR merges the annotations with existing annotations in the chart, replacing overlapping keys with the values that were generated by our automation.
=> Ensure chart annotations are merged with generated annotations on index creation

.github/workflows/build.yml
To help with CGO-related issues with chart-verifier built using golang 1.20.
=> Bump the GHA run image to ubuntu 22.04

tests/functional/behave_features/HC-16_chart_test_takes_more_than_30mins.feature, tests/functional/features/HC-16_chart_test_takes_more_than_30mins.feature
Chart Testing was bumped in recent development versions of chart-verifier. The error message now returns a go-multierror, it seems, which doesn't quite output the exact single line that our e2e tests are expecting. This PR makes the expected message a bit less specific to accommodate this change.
=> Adjust expected timeout message

release/release_info.json
Release a bugfix for chart-only PRs getting their annotations squashed when merged into the index.
=> Release 1.5.5

scripts/src/chartrepomanager/chartrepomanager.py
Resolves a bug where a community chart's annotations key is empty, so we run into a key error trying to merge annotations.
https://github.com/openshift-helm-charts/charts/actions/runs/5470196056/jobs/9959992719#step:34:204
=> assign annotations instead of merging in cases where there were no original annotations set

tests/data/HC-04/community/report.yaml, tests/data/HC-04/partner/report.yaml, tests/data/HC-04/redhat/report.yaml, tests/data/HC-06/partner/report.yaml, tests/data/HC-09/community/report.json, tests/data/HC-09/partner/report.json, tests/data/HC-09/redhat/report.json, tests/data/HC-10/signed_chart/report/partner/report.yaml, tests/data/HC-10/signed_chart/report/redhat/report.yaml, tests/data/HC-11/community/report.yaml, tests/data/HC-11/partner/report.yaml, tests/data/HC-11/partner_not_contain_crds/report.yaml, tests/data/HC-18/community/report.yaml, tests/data/HC-18/partner/report.yaml, tests/data/HC-18/redhat/report.yaml, tests/data/HC-19/report_edited_sha_bad/report.yaml, tests/data/HC-19/report_sha_bad/report.yaml, tests/data/HC-19/report_sha_good/report.yaml, tests/data/README.md, tests/data/common/community/report.yaml, tests/data/common/partner/report.yaml, tests/data/common/redhat/report.yaml
In the recent move to OCP 4.13 underpinning this repo's tests, one of the test charts would not run. That's been resolved, but in resolving that, we needed to regenerate various permutations of reports that use those charts as a base. 
This PR regenerates those reports.
=> Regenerate test reports after chart modifications

.github/workflows/test-cluster-access.yml
Whenever we update the pipeline to use a new cluster and provision a new service account, we update the repository secrets to make sure they're inline. This workflow allows a maintainer to make sure the credentials are correct after swapping that out via a button press (workflow dispatch).
See what this looks like here: https://github.com/komish/charts-development/actions/runs/5659433714/job/15332966926
=> Add workflow to test cluster access for credential and endpoint changes

release/release_info.json
This release contains mostly test fixture changes to support the OCP 4.13 release, and an additional convenience GHA to ensure cluster access when credentials/cluster endpoints are changed.
=> Release 1.5.7

.github/workflows/ci-enabled.yml, .github/workflows/test-ci-enabled.yml
In preparation for some replumbing that's will come in the near future, we need the ability to dynamically disconnect certification while also being able to re-run workflows so that we can retrigger them once we've finished our work.
This PR adds an action that fails if the input provided is not explicitly set to `true`. We feed it a contextual variable, in our case, the `CERTIFICATION_ENABLED` variable set at the repository, org, or environment level within the GitHub repo settings.
This isn't currently configured to block. For this PoC, I've also added a test workflow that can be manually called by developers to see if the workflow _would be blocked_. 
In a future iteration, I'll likely look to add this to the Certification workflows for the reason described above.
The requisite …
=> Create action to disable specific workflows based on repo config

tests/data/HC-04/community/report.yaml, tests/data/HC-04/partner/report.yaml, tests/data/HC-04/redhat/report.yaml, tests/data/HC-06/partner/report.yaml, tests/data/HC-09/community/report.json, tests/data/HC-09/partner/report.json, tests/data/HC-09/redhat/report.json, tests/data/HC-10/signed_chart/report/partner/report.yaml, tests/data/HC-10/signed_chart/report/redhat/report.yaml, tests/data/HC-11/community/report.yaml, tests/data/HC-11/partner/report.yaml, tests/data/HC-11/partner_not_contain_crds/report.yaml, tests/data/HC-18/community/report.yaml, tests/data/HC-18/partner/report.yaml, tests/data/HC-18/redhat/report.yaml, tests/data/HC-19/report_edited_sha_bad/report.yaml, tests/data/HC-19/report_sha_bad/report.yaml, tests/data/HC-19/report_sha_good/report.yaml, tests/data/common/community/report.yaml, tests/data/common/partner/report.yaml, tests/data/common/redhat/report.yaml
Unblocks #250
Summary:
* Regenerated reports for the vault charts that were updated due to recent breakage from a chart-verifier bugfix.
=> Updated reports for vault chart fixtures

.github/workflows/build.yml
The previous BOT_TOKEN value that was being used in the sandbox repo was another maintainer's PAT, which allowed us to approve PRs created by the openshift-helm-charts-bot in release workflows. That PAT expired, and in replacing it, we're running into issues because of the aforementioned 'user cannot approve their own workflow'.
This PR configures the Approve PR task to use the secrets.GITHUB_TOKEN available within GitHub Actions for the sandbox repository while still using the BOT_TOKEN in other contexts that don't have this problem.
=> use a separate approval token for the sandbox repository workflow

tests/functional/behave_features/HC-16_chart_test_takes_more_than_30mins.feature, tests/functional/behave_features/common/utils/chart_certification.py, tests/functional/features/HC-16_chart_test_takes_more_than_30mins.feature, tests/functional/utils/chart_certification.py
This PR **should**  fix the pipeline for https://github.com/openshift-helm-charts/development/pull/254
The reason for the failure is because in scenario `HC-16_chart_test_takes_more_than_30mins` for partners, we're expecting the string `* timed out waiting for the condition` in the PR comment. The time out does occur, and the PR does get a comment about a timeout, but it doesn't contains this exact string.
This is the PR in question FYI: https://github.com/openshift-helm-charts/sandbox/pull/65858
I dug around but I can't seem to understand how this was passing until now. They were a few recent changes that could have affected this, but I must be missing something because I can't find the culprit:
* github.com/helm/chart-testing/v3 updated from v3.8.0 to v3.9.0 in chart-verifier
* …
=> Adjust expected timeout message and accept regex in expected message

scripts/src/saforcertadmin/create_sa.sh
The script that's used to extract the token of the newly created service account on new clusters was referring to a path in the service account resource that doesn't exist anymore. This modification allows us to identify the right secret, and pull the token.
=> Refer to the correct secret during token extraction

scripts/src/chartprreview/chartprreview.py
This should allow `+` in the version of the folder path, and allow checkouts to happen.
```
charts/partners/yugabytedb/yugaware-openshift/2.18.2+1/report.yaml
```
[Link](https://pythex.org/?regex=charts%2F(%5Cw%2B)%2F(%5B%5Cw-%5D%2B)%2F(%5B%5Cw-%5D%2B)%2F(%5B%5Cw%5C.%5C-%2B%5D%2B)%2F.*&test_string=charts%2Fpartners%2Fyugabytedb%2Fyugaware-openshift%2F2.18.2%2B1%2Freport.yaml&ignorecase=1&multiline=0&dotall=0&verbose=1) to regex test
=> fixing regex to follow semver and allow +

scripts/src/workflowtesting/checkprforci.py
This PR fixes a bug in the logic that checks PR contents to detect if workflow files were modified.
PR https://github.com/openshift-helm-charts/development/pull/264 adds a composite action, and also modifies some of the workflows to utilize that composite action. In the testing of that PR, it seems that Workflow Tests didn't run.
This seems to be because the logic that would detect if workflow tests needed to run would fail early because the composite actions path did not match any of the expected paths that would trigger a workflow run.
I believe that the logic here is bugged such that files that don't match any of the expressions defined would cause the check to immediately return indicating that the PR contained non-workflow files and therefore shouldn't trigger workflow tests. …
=> Prevent early exit in cases where a non-workflow file is also modified alongside workflow files

.github/workflows/build.yml, scripts/src/checkprcontent/checkpr.py
Rename GitHub workflow outputs to use snake case for consistency purposes
=> Consistent github output names

.github/workflows/python-style.yml, .gitignore, scripts/Makefile, scripts/ruff.toml
This PR adds a:
1) A Makefile within the scripts/ directory for use in enforcing style and managing virtualenvs
2) a GitHub Actions that consumes the Makefile targets to enforce style guidelines for changes to tooling within the scripts/ directory
3) An expanded .gitignore to remove a lot of cruft that gets added to the filesystem when building/installing various CI tools.
We've previously [applied Black](https://github.com/openshift-helm-charts/development/pull/247) to the code in this repository, and fixed a few pep8 complaints. This just takes that a bit further and starts to enforce it on PRs.
Linting is currently configured to auto-pass because we have a lot of things that are not automatically fixable (namely import positioning and line length). The idea here is that, when so …
=> Add Python Code Style Enforcement to GitHub Actions

scripts/src/checkprcontent/checkpr.py, scripts/src/release/releasechecker.py, scripts/src/reporegex/matchers.py, scripts/src/signedchart/signedchart.py
In PR https://github.com/openshift-helm-charts/development/pull/269, we fixed an issue in the handling of plus sign values in our chart submission path (e.g. charts/partners/vendor/chartname/0.0.1+1/...) which was preventing us from successfully detecting valid files to modify/submit.
We fixed this in one location, but there are various locations that use nearly the same regex, some which did not include the exact same version support.
This PR extracts out the generation of that string to a library that can be called at any point.
The configurable keyword args were added simply to support the existing use cases in-repo (vs. altering those use cases). The goal here is to allow the library invocation to be compatible, and maybe iterate on how we handle matching these in the future (if …
=> Extract repo path regex matching to a single library and reconfigure scripts to use it

scripts/src/chartprreview/chartprreview.py, scripts/src/chartrepomanager/chartrepomanager.py, scripts/src/metrics/metrics.py
The most recent PR to update our use of submission path regex missed a couple of locations where this was being used, so this PR should address those locations.
=> Configure more locations to use the submission regex matchers

.github/workflows/build.yml
Update GitHub workflow actions from `redhat-actions` organization to versions that run on node 16.
This pull request:
* Updates `redhat-actions/openshift-tools-installer@v1` to `v1.12`
* Updates `redhat-actions/oc-login@v1` to `v1.2`
* Updates `redhat-actions/chart-verifier@v1.1` to `v1.2`
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
=> Update GH actions from redhat-actions to use node 16

docs/README.md
=> Fix name of the Partner Acceleration Desk

scripts/src/pullrequest/prepare_pr_comment.py
This is the first PR in an effort to restructure how we handle PR comments so it's a bit more reliable in our pipeline. This PR mostly just cleans up the library logic, and produces a formatted PR comment.
We currently don't have a templating dependency like Jinja, so I continued to leave any templating dependency out. For now. That might change in the future.
With that said, this PR adds helper functionality **append_to** that helps build the comment, and consolidates our use of multi-line strings (which visually breaks the flow of the source code), and manually managed line breaks to as few places as possible.
This PR also adds a 'Task Table' to the PR comment, which reflects what GitHub Action steps were considered in the production of the comment. We could make this more useful over …
=> Improve markdown comment formatting library and update PR comment format

.github/workflows/build.yml, scripts/src/pullrequest/prepare_pr_comment.py
The oc-install step doesn't continue-on-error, hence we should use .outcome instead of .conclusion to check if it runned successfully, was skipped or failed.
This information is never empty, hence there is no need to default the value of this argument to False in prepare_pr_comment.py.
Closes #287
=> Better handle oc-install outcome

.github/workflows/build.yml
At the moment, Metrics reporting is failing because the PR comment it needs is no longer available in the job where it runs.
https://github.com/openshift-helm-charts/charts/actions/runs/6709583883/job/18233057391#step:11:53
I believe that the metrics step can probably be extracted out into its own execution such that it doesn't cause the release step to fail, but until that gets prioritizes, this PR pulls the PR comment contents from the `chart-verifier` task and into the `release` task by encoding it in a step of the former job, and then writing it back to the expected location in a step of the latter job.
Definitely a temporary measure, but it's a quick way to get the release tasks to start passing. At the moment, I would expect them all to fail, even though all the actual releasing …
=> Make the PR comment accessible to the metrics step

.github/workflows/build.yml, scripts/setup.cfg, scripts/src/chartrepomanager/chartrepomanager.py, scripts/src/updateindex/updateindex.py
~Please do not review/merge just yet, I want to see the pipeline results before testing/applying further code optimizations~ READY !
So far the chart-repo-manager script had multiple functions:
* Create the GitHub Release (only if the chart's sources are provided)
using chart-releaser.
* Prepare the index entry for this chart.
* Update the Helm repository index.
In addition, a separate step in our build.yaml workflow added the
report.yaml to the GitHub release (potentially creating it, in the case
the chart's sources are not provided).
This commit brings the following changes:
* Reduce the role of the chart-repo-manager script to a) the preparation
of all artifacts that go into a GitHub Release, and b) the crafting of
the index entry.
* Consolidate the GitHub release creation and the …
=> Consolidate Github release management in one step

.github/workflows/build.yml, scripts/src/chartrepomanager/chartrepomanager.py, scripts/src/updateindex/updateindex.py
This commit gets rid of the json.loads() call as the argparse type for chart_entry in update-index. Instead we now encode the index entry to base64 in chart-repo-manager before adding it to the GITHUB_OUTPUT and decode it in update-index back to a dict.
This allows the use of double quotes when passing the "--chart-entry" argument to update-index, which enables the possibility for variable evaluation. This paves the way for using environment variables instead of using step's output directly.
=> Encode chart_entry to base64

.github/workflows/build.yml
Partners will see a failed automation if our metrics collection step fails. We might benefit from moving this workflow to be separate from the CI job, but for now, I'm marking these as continue-on-error and adding a notification that should hit the helm_dev slack channel (which is where we currently see nightly run failures).
The Slack token might need updating in the production repo, but we'll do that when the first certification comes through after this gets released.
=> Do not fail certifications if metrics population fails

.github/workflows/test.yml
Credit to @nickboldt for this work. PR has been pulled from the `openshift-helm-charts/charts` repository.
GH action https://github.com/openshift-helm-charts/charts/actions/workflows/test.yml seems to be failing for the last few PR checks. This change might solve that problem?
However I'm not auth'd to run workflow code updates on this repo:
```
```
So a code owner will have to run this.
References:
https://github.com/openshift-helm-charts/charts/pull/1136
=> chore: use the same checkout configuration in test.yml as in build.yml

.github/workflows/test.yml
This reverts commit 06f0ba1df4bea2cc2662c0c93920c1474be47eb1.
See reasoning here: https://github.com/openshift-helm-charts/development/issues/305#issuecomment-1861431769
=> Revert 'chore: use the same checkout configuration in test.yml as in build.yml (#306)'

.github/workflows/check-contributor.yml, .github/workflows/release.yml, .github/workflows/test.yml, scripts/setup.cfg, scripts/src/owners/user_is_repo_owner.py
Borrows from our existing user check scripts to generate a smaller script that we can throw into various workflows as needed.
Some of our workflows fail for certification attempts even though they aren't associated with certification. In this cases, it makes sense to avoid having them run, but we still need them to run on pull requests. This PR introduces a workflow that gates those PRs so they don't run if the user isn't a repository owner. This gives the green check for partners/chart contributors (because the dependent workflow skips), but still allows us to use these workflows for their original use cases.
=> Add contributor check gate

scripts/ruff.toml, scripts/src/chartprreview/chartprreview.py, scripts/src/chartprreview/chartprreview_test.py, scripts/src/chartrepomanager/chartrepomanager.py, scripts/src/chartrepomanager/indexannotations.py, scripts/src/checkautomerge/checkautomerge.py, scripts/src/checkprcontent/checkpr.py, scripts/src/indexfile/index.py, scripts/src/metrics/metrics.py, scripts/src/metrics/pushowners.py, scripts/src/owners/checkuser.py, scripts/src/owners/user_is_repo_owner.py, scripts/src/pullrequest/prartifact.py, scripts/src/pullrequest/prepare_pr_comment.py, scripts/src/release/release_info.py, scripts/src/release/releasechecker.py, scripts/src/release/releaser.py, scripts/src/report/get_verify_params.py, scripts/src/report/report_info.py, scripts/src/report/verifier_report.py, scripts/src/saforcertadmin/push_secrets.py, scripts/src/saforcharttesting/saforcharttesting.py, scripts/src/signedchart/signedchart.py, scripts/src/tools/gitutils.py, scripts/src/updateindex/updateindex.py, scripts/src/workflowtesting/checkprforci.py
This PR extends the Ruff configuration to add a barebones, mostly isort-compatible import sorting linter. With the `ruff check --fix` flag, this sorts imports in-place in a similar style. Reasonable to expect: alphabetical per group, E.g. stdlib, local, external)
=> Add tool-enforced import sorting

scripts/setup.cfg, scripts/src/owners/owners_file.py, scripts/src/owners/redhat_metadata.py, scripts/src/packagemapping/generatelocks.py, scripts/src/pullrequest/metadata.py
- The owners module changes enables parsing Red Hat OWNERS files and asserting that metadata meets new expectations of the content.
- The packagemapping module provides hooks to generating chart locks based on the content of a given repository's charts/ directory.
- The pullrequest module changes facilitates asserting metadata given a pull request as an input.
- Entrypoints are then added to setup.cfg to simplify calling of this new logic in CI.
Depends on https://github.com/openshift-helm-charts/development/pull/313 for Python Style to pass.
=> Enable metadata assertion and chart lock generation

.gitignore
I use Pyenv on my machine to get the right version of Python installed locally, matching GHA. This ignores the cookie file that Pyenv reads.
=> Ignore pyenv cookie files

.github/actions/check-chart-locks/action.yml, .github/actions/generate-chart-locks/action.yaml
These actions will read the given state of the repository and determine what chart names are associated with what filesystem paths. they're designed to prevent charts being stored with the same name.
These actions currently have no callers, but a non-break worfklow dispatch can be added to test their functionality before they're integrated into CI-breaking workflows.
An example of how check-chart-locks would be called:
```yaml
- name: Check if chart name is locked
id: determine-lock-status
uses: ./.github/actions/check-chart-locks
with:
chart-name: ${{ steps.gather-metadata.outputs.chart-name }}
fail-workflow-if-locked: 'false'
```
An example of how generate-chart-locks would be called:
```yaml
- name: Generate Locks
id: generate-locks
uses: ./.github/actions/generate-chart-locks
```
=> Adds composite actions to generate and check locks

tests/functional/behave_features/common/utils/chart_certification.py, tests/functional/behave_features/common/utils/e2e_templates.py, tests/functional/behave_features/common/utils/github.py, tests/functional/behave_features/common/utils/owner_file_submission.py, tests/functional/behave_features/common/utils/setttings.py, tests/functional/behave_features/common/utils/workflow_repo_manager.py
**WorkflowRepoManager** provides some basic hooks into the operations we take against the local GitHub repository (e.g. adding branches, worktrees), and in some cases, the remote. This allows us to more effectively clean up after ourselves locally/remotely.
The end goal for this is to refactor the chart certification workflow to use it in the future.
**OwnersFileSubmissionE2ETest** is a net-new E2E testing class, supporting the testing of OWNERS file submissions from the user, and ensuring certain things take place when that's done.
The rest of the changes support these net new components.
---
Note that there are some changes that impact the production chart_certification script. These changes are minimally impactful to the code, and should be non-impactful to the execution of these in …
=> Adds scripts required to support OWNERS file testing and Workflow repository management.

scripts/src/chartrepomanager/chartrepomanager.py, scripts/src/owners/owners_file.py, scripts/src/report/verifier_report.py
- YAML files added in PRs are considered untrusted (new OWNERS, report.yaml, ...)
- files already commited to the repository are considered trusted (exising OWNERS, current Helm repo index)
=> Use SafeLoader when loading untrusted YAML

tests/functional/behave_features/common/utils/github.py
When E2E tests fails due to a sandbox PR not running the expected Workflow, the PR number was until now not displayed, making it difficult to figure out which PR to look at in oder to get more information. This commit adds the PR number to the raised Exception message to make it visible in the workflow logs directly.
=> Add more debug information when E2E tests fail

.github/actions/generate-chart-locks/action.yaml, scripts/src/packagemapping/generatelocks.py
- Fixes a bug in new actions where the virtualenv `ve1` would be expected to be in the current working directory, but is typically built up one level.
- Adds a shell flag to exit on pipefail for a given task.
- Replaced some camel case variables with snake case equivalents (for style points!)
=> Correct default virtualenv location

.github/workflows/check-locks-on-owners-submission.yml, .github/workflows/lock-sanity-check.yml, .github/workflows/owners-redhat.yml, scripts/src/checkprcontent/checkpr.py, tests/functional/behave_features/HC-20_owners_file.feature, tests/functional/behave_features/common/utils/chart_certification.py, tests/functional/behave_features/environment.py, tests/functional/behave_features/steps/implementation_owners.py
~Do Not Merge.~
~I will remove :point_up: if and when this this is valid to merge/review. I have intentionally not applied the *draft* label because this prevents certain CI operations from running.~
[EDIT] This is ready for review.
---
This PR contains all of the impactful changes to how the certification pipeline works in order to resolve issues when depending on charts we provide.
In effect, this PR enables:
- Locked helm chart name tracking and generation
- Checks on OWNERS file submission to ensure locks are respected
- Fixes indexing strategy to index on chart names only
In addition, this PR includes E2E testing extensions for some of the new logic.
---
Change summary by file:
.github/workflows/mercury_bot.yml
- Only run this on changes to partner OWNERS files.
- Make sure that the …
=> Implement bugfix for chart dependencies and gitops.

scripts/requirements.txt, scripts/src/checkprcontent/checkpr.py, scripts/src/precheck/serializer.py, scripts/src/precheck/serializer_test.py, scripts/src/precheck/submission.py, scripts/src/precheck/submission_test.py
This is the first step towards solving #296. The code added by this commit is currently *not* put in use in the certification pipeline and is a partial duplicate of the "checkprcontent" package.
The Submission data structure can collect and run early validation checks on all information concerning a user's submission (i.e. a GitHub Pull Request). In its current state, given an api_url (link to a given PR), it can collect the list of modified files, and extract the category, organization, chart's name and version, as well as running basic checks, such as SemVer compatibility of the provided version.
Eventually, this data structure is meant to encapsulate more information concerning the user's submission, and be dumped to a json file (using JSONEncode / JSONDecoder, more on that in a later …
=> Initialize the Submission data structure

.github/workflows/owners-redhat.yml
Fixes #337
In testing this workflow used exactly these tokens (GITHUB_TOKEN and BOT_TOKEN) throughout without issue, as written. E.g. https://github.com/komish/openshift-helm-charts/actions/runs/7935140662/job/21667629787#step:6:19
I think, because I'm the repository owner in that case, that there may have been special access to secrets that I don't have in the openshift-helm-charts/charts repository.
This PR changes the trigger to pull_request_target. Remember that we have to be conscious on what code we run when we do that, particularly if we pull the PR branch itself.
Here, I pull the PR branch after all scripts have been installed from the main branch, just so I have access to the OWNERS file, and so I can assert metadata on it. Nothing is executed from the pulled PR branch. This is …
=> Allow token access to redhat OWNERS file metadata check automation

.github/workflows/build.yml
Add a GitHub comment if an error occurs during the update of the helm index that pings the maintainers.
fix #341
=> Ping maintainers if the release job fails

tests/functional/behave_features/common/utils/chart_certification.py
https://github.com/openshift-helm-charts/development/actions/runs/8778116626 Failed with:
```
2024-04-22T07:35:12.3970113Z       Traceback (most recent call last):
2024-04-22T07:35:12.3979348Z         File "/home/runner/work/development/development/ve1/lib/python3.10/site-packages/behave/model.py", line 1329, in run
2024-04-22T07:35:12.3980225Z           match.run(runner.context)
2024-04-22T07:35:12.3981201Z         File "/home/runner/work/development/development/ve1/lib/python3.10/site-packages/behave/matchers.py", line 98, in run
2024-04-22T07:35:12.3981996Z           self.func(context, *args, **kwargs)
2024-04-22T07:35:12.3982867Z         File "tests/functional/behave_features/steps/implementation.py", line 272, in user_sends_a_pull_request
2024-04-22T07:35:12.3983665Z …
```
=> Add debug information when tests fail to create PR

tests/data/HC-17/plus-in-version/partner/report.yaml, tests/data/HC-17/plus-in-version/redhat/report.yaml, tests/functional/behave_features/HC-17_dash_in_version.feature
Summary:
* Added a new test scenario (HC-17-002) which tests a chart with a plus sign in the version
* Includes a pair of reports (`partner` and `redhat` vendor types) referencing a helm chart.tgz with a plus in the version
=> Added new test scenario plus-in-version to HC-17

scripts/src/owners/owners_file.py, scripts/src/report/verifier_report.py
Add a "success" return value to get_web_catalog function to inform the caller if the file (OWNERS or report.yaml) doesn't contain such a key.
While this is currently not used by callers, this is a pre-requisite for #344 to exit draft status
=> Inform caller if web_catatog_only key is missing

release/release_info.json
Summary:
* Standardize action runner versions across workflows by @komish in https://github.com/openshift-helm-charts/development/pull/339
* Correctly determine the OWNERS file change type by @komish in https://github.com/openshift-helm-charts/development/pull/340
* Initialize the Submission data structure by @mgoerens in https://github.com/openshift-helm-charts/development/pull/332
* Allow token access to redhat OWNERS file metadata check automation by @komish in https://github.com/openshift-helm-charts/development/pull/338
* Remove unused function in 'signed_chart.py' by @mgoerens in https://github.com/openshift-helm-charts/development/pull/322
* Ping maintainers if the release job fails by @mgoerens in https://github.com/openshift-helm-charts/development/pull/343
* Rework …
=> Release v1.7.1

scripts/src/packagemapping/generatelocks.py
The return values for `owners_file.get_owner_data_from_file` was [changed recently](https://github.com/openshift-helm-charts/development/pull/321) such that it no longer returns a boolean reflecting whether accessing the OWNERS file was successful, instead favoring a Raised exception. 
This PR updates the chart lock generation logic. See https://github.com/openshift-helm-charts/charts/actions/runs/9470017334
=> Wrap owners file content access function in try except

.github/dependabot.yml, release/release_info.json
- Repository configuration will be updated to enable dependabot after this merges.
- Release info updated so that this configuration doesn't end up in the various other downstream repos.
=> Add dependabot configuration for core scripts

scripts/src/precheck/submission.py, scripts/src/precheck/submission_test.py
This is a port of the two following checks, performed at the end of the
checkpr script, to the Chart data structure:
* Check that the Chart in this version is not already present in the
index
* Check that the release tag for this chart doesn't already exists on a
given GitHub repository
Reviewers, please see https://github.com/openshift-helm-charts/development/blob/main/scripts/src/checkprcontent/checkpr.py#L224-L276 for the original code (still in use at the moment).
=> Ports checks if a chart is in index; and if a release tag already exists

scripts/src/saforcertadmin/create_sa.sh, scripts/src/saforcertadmin/token_secret.yaml, scripts/src/saforcharttesting/saforcharttesting.py
Fixes #365 
For the saforcertadmin scripts, we would previously detect the service account secret and read that for the token value. Since we now know the name of the secret, the logic becomes simpler.
For the saforcharttesting scripts, we just add an additional resource to be created. I left the parsing logic intact as it seems to work in my testing, and remains backwards compatible (not that we really need that here).
=> Ensure service account token generation for workflows

.github/workflows/build.yml
For whatever reason, the openshift-tools-installer action now takes 3 minutes in our workflow, and we call it ~3 times. On a bad day, that's causing the containing steps to take 4x their normal duration, which is in turn adding enough time to cause our nightly tests (and presumably full E2E) to fail with a 6 hour timeout.
I observed that enabling caching will speed this back up, but disabling the cache has been a conscious decision because of our reuse of the 0.1.0 tag in chart-verifier. That is, we delete and recreate the 0.1.0 as our development release, always reflecting main. By caching, we run the risk of not properly testing new chart-verifier changes as they happen because we may pull an old binary from the cache.
We'll see if that pans out, but for now, we need to release sometime …
=> Workaround openshift-tools-installer taking an extra 3 minutes per executions

.github/workflows/build.yml, .github/workflows/test-cluster-access.yml
The previously implemented workaround saved us some time, but not enough. It looks like the core issue is that node20 is actually running for workflows that run are setup to use node16. In my testing, node20 exhibits the issue but node 16 and 18 do not, so I'm temporarily enabling node16 until we can get the tools installer to bump their version.
Also reverting the disabled cache.
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> Allow actions to use node16 temporarily

.github/workflows/build.yml, .github/workflows/test-cluster-access.yml
With the merging of https://github.com/redhat-actions/openshift-tools-installer/pull/106, the openshift-tools-installer should now be using a Node20 runtime and the issue that was previously observed (3 minute delay for every execution) is now resolved.
This PR removes the workaround that was put in place that allowed a Node16 runtime to be used after its deprecation timeline.
As a sidenote, the openshift-tools-installer@v1.13 is already in use in the pipeline because the PR linked previously is included in the v1 resolution - so we're already using it  we just don't need this environment variable anymore. 
See [here](https://github.com/openshift-helm-charts/sandbox/actions/runs/10091049137/job/27901790294#step:1:39), the commit hash corresponds to …
=> Remove openshift-tools-installer workaround

scripts/src/saforcharttesting/saforcharttesting.py
In https://github.com/openshift-helm-charts/development/pull/366, I modified the code that creates namespaces, RBAC resources, etc. used in certification workflows because OpenShift 4.16 (which is our current runtime platform) did not automatically populate tokens for the service accounts. In effect, I just manually created a secret so that the cluster would populate it with a token we could use.
Since then, I've noticed we had intermittent failures in nightly runs. 
https://github.com/openshift-helm-charts/sandbox/actions/runs/10060735219/job/27809079797#step:17:18
When we search for the service account token, we parse the service account in the temporary namespace to see if it has secrets populated. In certain (or all modern) cases, the token secret may not be listed in the service …
=> Extract temporary service account token by name directly

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/mercury_bot.yml, .github/workflows/release.yml, .github/workflows/test.yml
I'm seeing warnings from our actions run that these actions are using the Node16 runtime, which is deprecated and is transparently being replaced with the Node20 runtime. 
This PR advances these actions to versions that explicitly use the Node20 runtime.
=> Update actions still running in Node16 to their Node20 equivalents

.github/workflows/check-contributor.yml, .github/workflows/ci-enabled.yml, .github/workflows/codeql.yml, .github/workflows/mercury_bot.yml, .github/workflows/metrics.yml, .github/workflows/nightly_test.yml, .github/workflows/owners.yml, .github/workflows/python-style.yml, .github/workflows/python-test.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/version_check.yml
This replaces all ubuntu-* references that are not 22.04 to explicitly use 22.04 (which is the equivalent of ubuntu-latest at the time of this writing)
=> Standardize runner images to ubuntu-22.04

scripts/src/pullrequest/prepare_pr_comment.py
This GitHub output doesn't seem to be needed anymore as it's not used anywhere.
=> Remove unused GitHub output

scripts/src/submission/submission.py, scripts/src/submission/submission_test.py
This mimics the current behavior, see: https://github.com/openshift-helm-charts/development/blob/3ac6de443b51d842c4438d9d4922b58b37bbe4c3/scripts/src/checkprcontent/checkpr.py#L36
When `get_web_catalog_only` is called without `raise_if_missing=True` it defaults to `False`.
=> Assume webCatalogOnly=False if not found in OWNERS

scripts/src/submission/submission.py, scripts/src/submission/submission_test.py
End to end tests expect specific messages to be present in the failed PR comments.
This PR aligns the error message from the submission module so that end to end tests may pass.
For instance: https://github.com/openshift-helm-charts/development/blob/main/tests/functional/behave_features/HC-06_provider_delivery_control.feature#L46-L47
=> Match error message with end to end tests

scripts/src/submission/submission.py, scripts/src/submission/submission_test.py
When validating that a PR contains the correct set of file to certify a chart, this PR adds the possibility to ignore the fact that an OWNERS file is also present.
While an OWNERS file should never be present in this type of submission, the case of an invalid Submission containing a mix of OWNERS and other files is handled in the is_valid_owners_submission method.
Eventually, errors related to OWNERS file (which this belongs to) feed the owners-error-message GITHUB OUTPUT, while other errors feed the pr-content-error-message GITHUB OUTPUT.
EDIT: Current behavior can be checked in the checkpr module starting here: https://github.com/openshift-helm-charts/development/blob/3ac6de443b51d842c4438d9d4922b58b37bbe4c3/scripts/src/checkprcontent/checkpr.py#L120
=> Allow ignoring the presence of an OWNERS file

scripts/src/submission/submission.py
Also fixes the default github pages branch value.
Note that this was previously discussed [here](https://github.com/openshift-helm-charts/development/pull/347#discussion_r1630297722) and it was decided *against* initializing a empty index in that case.
However, the sandbox repo does not contain any index, hence, the end to end tests are failing when running this code.
Potentially this can be fixed by creating an empty (or not empty) index on the gh-pages branch of the sandbox repo, however I haven't looked into the other potential implication of doing so.
=> Generate a valid empty index when none is found

.github/workflows/build.yml
Index update commit messages no longer have the chart's release information (i.e. org-chartname-version).  This is because there is data not being transferred across jobs in the certification workflow.
The `RELEASE_TAG` environment variable is used in this script, but has no value assigned to it. It's being set in a previous job, so we can easily pass along this variable to this script.
=> fix missing RELEASE_TAG value for index update commits

.github/actions/generate-chart-locks/action.yaml, .github/actions/setup-python/action.yml, .github/workflows/build.yml, .github/workflows/check-contributor.yml, .github/workflows/check-locks-on-owners-submission.yml, .github/workflows/lock-sanity-check.yml, .github/workflows/mercury_bot.yml, .github/workflows/metrics.yml, .github/workflows/nightly_test.yml, .github/workflows/owners-redhat.yml, .github/workflows/owners.yml, .github/workflows/python-style.yml, .github/workflows/python-test.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/version_check.yml
This PR just consolidates the installation of python into a single place in-repo that can be reused across workflows. In practice, this should allow us to update a single place as the python version advances and have it impact all workflows of interest. 
In the future, we can potentially do this exact same thing with the installation of the CI scripts. Task for another day.
=> Consolidate setup-python version definition to one place

scripts/src/release/releaser.py
If a maintainer removed a file from the repository that was "ignored" in the release_info.json, which controls the syncing of repositories, the release process would fail. In the case a FileNotFoundError is thrown by either the `shutil.rmtree` or `os.remove` commands during the ignore process, we should treat it as non-fatal given the outcome is the same (the file does not exist in the destination repository).
=> ignore not found errors for ignored files that are not found in dest repo

.github/workflows/behave.yml
We keep hitting GitHub API limits in nightly testing, which causes failures that succeed in a re-run. I'll spend time in early 2025 investigating what can be done to optimize our API usage, but for the moment, this PR will reduce the concurrency operations to see if it helps get us past these issues until then.
I intend to measure our API usage more aggressively to determine a better course of action in the near future.
=> Reduce concurrency to lower API rate limiting frequency

tests/functional/behave_features/common/utils/workflow_repo_manager.py
Upon initialization, WorkflowRepoManager registers the repository original branch, so that it can return to that branch during cleanup. If the tests are run on a detached HEAD, this operation fails as it expects to be on a git branch.
This commit adds a failover to handle that particular case, defaulting to using the commit ID.
=> Failover register original branch in repo_manager

tests/functional/behave_features/common/utils/github.py
During end to end tests, we query the GitHub API regularly to check if the pipeline associated with the test PR has completed. This commit increase the retry timeout in order to decrease the total amount of API calls that the bot account is performing. This helps with staying within the GitHub API rate limits as highlighted in #422.
=> Increase retry timeout when polling CI run result

.github/workflows/build.yml
The redhat-actions/openshift-tools-installer is experiencing slowness when installing oc. This steps can take up to 3 minutes. More info: https://github.com/redhat-actions/openshift-tools-installer/issues/105
Using a custom script reduces the installation of oc to less than 10s.
=> Install oc without external action

.github/workflows/build.yml, scripts/src/report/get_verify_params.py, scripts/src/submission/submission.py, scripts/src/submission/submission_test.py, scripts/src/updateindex/updateindex.py
This commit doesn't change the behavior of the get-verify-param step. It
builds upon the new Submission data structure to avoid additional calls
to the GitHub API and improve some readability aspects of the code.
This commit also introduces a slight modification to the Submission data
structure. Previously, the path related to the chart's source pointed to
the "./src/Chart.yaml" file, it now points to the "./src" directory.
This is useful as this is one of the return value of
generate_verify_options.
Finally, this commit also changes the SUBMISSION_PATH environment
variable to an absolute path. This way, steps that run from within the
"./pr-branch" directory such as get-verify-param can easily load the
submission artifact. Note that $GITHUB_WORKSPACE is the default path
under which load …
=> Refactor get verify params

tests/functional/behave_features/common/utils/workflow_repo_manager.py
Previously we were assigning values to attributes on the class level. For list in particular, this had the side effect of leaking values between instances:
```
>>> m = OwnersFileSubmissionsE2ETest()
>>> m.repo_manager._WorkflowRepoManager__local_branches_created
['e2e-owners-d376dfa-6d3820eb5c624ddc9066f96f1a69640e']
>>> m.cleanup()
>>> m.repo_manager._WorkflowRepoManager__local_branches_created
[]
>>> m = OwnersFileSubmissionsE2ETest()
>>> m.repo_manager._WorkflowRepoManager__local_branches_created
['e2e-owners-d376dfa-6d3820eb5c624ddc9066f96f1a69640e', 'e2e-owners-d376dfa-cc7f8acf1850498cb6c758bc286f2bec']
```
Using a dataclass for WorkflowRepoManager, we can ensure that empty lists are initialized for each new instance, and attributes values remain independant.
Fix #414
=> Instanciate new empty lists for each instance of WorkflowRepoManager

.github/actions/install-ci-scripts/action.yml, .github/actions/setup-python/action.yml, .github/workflows/behave.yml, .github/workflows/build.yml, .github/workflows/check-contributor.yml, .github/workflows/check-locks-on-owners-submission.yml, .github/workflows/lock-sanity-check.yml, .github/workflows/mercury_bot.yml, .github/workflows/metrics.yml, .github/workflows/owners.yml, .github/workflows/python-test.yml, .github/workflows/release.yml, .github/workflows/test.yml
Installation of the python dependencies and scripts is done at the start of each job within the build.yaml workflow.
By caching the venv we can save up to 10 seconds on each job after the first.
**NOTE FOR REVIEWERS:** This builds upon #419 and should hence be merged after. Currently it also contains the commit of #419 but we should rebase before merging.
=> Cache virtualenv between jobs

scripts/src/metrics/metrics.py
The PyGithub library was updated in this pull request: https://github.com/openshift-helm-charts/development/pull/439.,
It introduced a documented breaking change when requesting rate limit information via the Github object. This pull request implements the changes suggested in their [changelog](https://github.com/PyGithub/PyGithub/blob/ad278c5f33931c33f374de5d03a3f3d0831c4aaf/doc/changes.rst?plain=1#L13-L25) and adds some documentation while I'm working with this function.
Should resolve issues with the "Scheduled Metrics" workflow.
=> use new RateLimitOverview class to check GitHub rate limit information

.github/workflows/build.yml
Testing to see if event base ref is present even if GITHUB_REF or the context-provided value is not. We may merge this to observe the behavior of a failing nightly when the GITHUB_REF value's are empty and fail a workflow.
=> Add event base ref for debugging

.github/workflows/build.yml
This PR introduces the RESOLVED_GITHUB_REF environment variable for the primary workflow evaluating chart submissions.
Fixes #432
This code change will use github.event.pull_request.base.ref instead of github.ref in cases where github.ref is not populated by in the GitHub Runner. In the event github.event.pull_request.base.ref is empty, this should produce an empty RESOLVED_GITHUB_REF, which should break the workflow and prompt a maintainer to intervene. This should only happen if the event type is not as expected, and so comments have been added to the workflow to indicate to maintainers (in the future) of the tight relationship between the event type and the underlying logic.
=> Resolve github.ref manually for certification workflow process
